library(tidyverse)
library(readxl)

fqa_data <- read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E1F1.xlsm",
                       sheet = "FQAResult",
                       range = "A8:B56")|>
  mutate((read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E1F2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E1N1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E1N2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E2F1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E2F2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E2N1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E2N2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E3F1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E3F2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E3N2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/E3N3.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W1F1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W1F2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W1N1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W1N2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W2N1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W2N2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W3F1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W3F2.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W3N1.xlsm",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W2F1_reconstructed.xlsx",
                     sheet = "FQAResult",
                     range = "B8:B56")),
         (read_excel("C:/Users/yacordob/OneDrive - North Carolina State University/Fines Study Documents/FQA Documents/W3N2_reconstructed.xlsx",
                     sheet = "FQAResult",
                     range = "B8:B56"))
  )|>
  
  drop_na(SampleId)

saveRDS(fqa_data, "raw_data/fqa_data.rds")